AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 26

Metrics/ClassLength:
  Max: 500
  
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassVars:
  Enabled: false
